****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [1]:
import pandas as pd
import json
from pandas.io.json import json_normalize
import numpy as np

In [2]:
sample_json_df = pd.read_json('data/world_bank_projects.json')
sample_json_df.head()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Percent': 100, 'Name': 'Education for all'}","[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Percent': 30, 'Name': 'Other economic manage...","[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Percent': 46, 'Name': 'Regional integration'}","[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Percent': 50, 'Name': 'Participation and civ...","[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,"{'Percent': 30, 'Name': 'Export development an...","[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [4]:
#Group the rows by country names and count them. 
sample_group = sample_json_df.groupby('countryshortname').count()
sample_group

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,docty,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
countryshortname,,,,,,,,,,,,,,,,,,,,,
Afghanistan,6,6,6,6,6,5,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
Africa,11,11,11,11,11,7,11,11,11,10,...,11,11,11,11,11,11,11,11,11,11
Albania,4,4,4,4,4,2,4,4,4,2,...,4,4,4,4,4,4,4,4,4,4
Angola,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Antigua and Barbuda,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Argentina,2,2,2,2,2,0,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Armenia,8,8,8,8,8,6,8,8,8,5,...,8,8,8,8,8,8,8,8,8,8
Azerbaijan,4,4,4,4,4,1,4,4,4,3,...,4,4,4,4,4,4,4,4,4,4
Bangladesh,12,12,12,12,12,10,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
Belarus,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Benin,4,4,4,4,2,3,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Bhutan,4,4,4,4,4,3,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Bolivia,2,2,2,2,2,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Bosnia and Herzegovina,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Brazil,9,9,9,9,9,8,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
Burkina Faso,9,9,9,9,9,8,9,9,9,7,...,9,9,9,9,9,9,9,9,9,9
Burundi,4,4,4,4,4,2,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Cambodia,2,2,2,2,2,1,2,2,2,1,...,2,2,2,2,2,2,2,2,2,2
Cameroon,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Cape Verde,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Central African Republic,1,1,1,1,1,0,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
Chad,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Chile,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
China,19,19,19,19,19,16,19,19,19,19,...,19,19,19,19,19,17,17,19,19,19
Colombia,3,3,3,3,2,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
Comoros,3,3,3,3,3,2,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
"Congo, Democratic Republic of",6,6,6,6,6,4,6,6,6,5,...,6,6,6,6,6,6,6,6,6,6
"Congo, Republic of",1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Costa Rica,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Cote d'Ivoire,4,4,4,4,4,2,4,4,4,3,...,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sao Tome and Principe,2,2,2,2,2,2,2,2,2,1,...,2,2,2,2,2,2,2,2,2,2
Senegal,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Serbia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Seychelles,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Sierra Leone,2,2,2,2,1,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Solomon Islands,3,3,3,3,3,1,3,3,3,2,...,3,3,3,3,3,3,3,3,3,3
South Asia,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
South Sudan,3,3,3,3,3,2,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
Sri Lanka,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Sudan,4,4,4,4,4,1,4,4,4,3,...,4,4,4,4,4,4,4,4,4,4
Tajikistan,8,8,8,8,8,6,8,8,8,7,...,8,8,8,8,8,8,8,8,8,8
Tanzania,8,8,8,8,8,4,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
Thailand,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Timor-Leste,2,2,2,2,2,0,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Togo,3,3,3,3,3,2,3,3,3,2,...,3,3,3,3,3,3,3,3,3,3
Tonga,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tunisia,4,4,4,4,4,3,4,4,4,3,...,4,4,4,4,4,4,4,4,4,4
Turkey,4,4,4,4,4,4,4,4,4,3,...,4,4,4,4,4,4,4,4,4,4
Tuvalu,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Uganda,4,4,4,4,4,3,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Ukraine,4,4,4,4,4,1,4,4,4,3,...,4,4,4,4,4,4,4,4,4,4
Uruguay,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
Uzbekistan,5,5,5,5,5,1,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Vanuatu,3,3,3,3,2,2,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
Vietnam,17,17,17,17,17,14,17,17,17,16,...,17,17,17,16,17,17,17,17,17,17
West Bank and Gaza,6,6,6,6,6,4,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
World,2,2,2,2,2,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
"Yemen, Republic of",13,13,13,13,13,8,13,13,13,11,...,13,13,13,13,13,13,13,13,13,13
Zambia,4,4,4,4,4,4,4,4,4,3,...,4,4,4,4,4,3,3,4,4,4
Zimbabwe,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [5]:
#Sort the countries by their count in project ID.
country_sorted = sample_group.sort_values('_id', ascending = False)
country_sorted

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,docty,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
countryshortname,,,,,,,,,,,,,,,,,,,,,
China,19,19,19,19,19,16,19,19,19,19,...,19,19,19,19,19,17,17,19,19,19
Indonesia,19,19,19,19,19,15,19,19,19,14,...,19,19,19,19,19,19,19,19,19,19
Vietnam,17,17,17,17,17,14,17,17,17,16,...,17,17,17,16,17,17,17,17,17,17
India,16,16,16,16,15,13,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
"Yemen, Republic of",13,13,13,13,13,8,13,13,13,11,...,13,13,13,13,13,13,13,13,13,13
Nepal,12,12,12,12,11,7,12,12,12,12,...,12,12,12,12,12,11,11,12,12,12
Bangladesh,12,12,12,12,12,10,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
Morocco,12,12,12,12,12,11,12,12,12,10,...,12,12,12,12,12,11,11,12,12,12
Mozambique,11,11,11,11,11,9,11,11,11,10,...,11,11,11,11,11,11,11,11,11,11
Africa,11,11,11,11,11,7,11,11,11,10,...,11,11,11,11,11,11,11,11,11,11
Pakistan,9,9,9,9,9,7,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
Brazil,9,9,9,9,9,8,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
Burkina Faso,9,9,9,9,9,8,9,9,9,7,...,9,9,9,9,9,9,9,9,9,9
Armenia,8,8,8,8,8,6,8,8,8,5,...,8,8,8,8,8,8,8,8,8,8
Tanzania,8,8,8,8,8,4,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
Tajikistan,8,8,8,8,8,6,8,8,8,7,...,8,8,8,8,8,8,8,8,8,8
Jordan,7,7,7,7,7,5,7,7,7,5,...,7,7,7,7,7,7,7,7,7,7
Nigeria,7,7,7,7,7,6,7,7,7,6,...,7,7,7,7,7,7,7,7,7,7
Lao People's Democratic Republic,7,7,7,7,6,6,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
Kyrgyz Republic,7,7,7,7,7,3,7,7,7,6,...,7,7,7,7,7,7,7,7,7,7
Kenya,6,6,6,6,6,5,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
"Congo, Democratic Republic of",6,6,6,6,6,4,6,6,6,5,...,6,6,6,6,6,6,6,6,6,6
Peru,6,6,6,6,5,5,6,6,6,5,...,6,6,6,6,6,6,6,6,6,6
Nicaragua,6,6,6,6,6,4,6,6,6,5,...,6,6,6,6,6,6,6,6,6,6
Afghanistan,6,6,6,6,6,5,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
West Bank and Gaza,6,6,6,6,6,4,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
Honduras,5,5,5,5,4,2,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Haiti,5,5,5,5,5,4,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Niger,5,5,5,5,5,4,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Liberia,5,5,5,5,5,4,5,5,5,4,...,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Marshall Islands,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
"Egypt, Arab Republic of",2,2,2,2,2,2,2,2,2,1,...,2,2,2,2,2,2,2,2,2,2
Mauritania,2,2,2,2,2,2,2,2,2,1,...,2,2,2,2,2,1,1,2,2,2
Mauritius,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Mexico,2,2,2,2,2,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Mongolia,2,2,2,2,2,1,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Ecuador,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Cape Verde,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Central African Republic,1,1,1,1,1,0,1,1,1,0,...,1,1,1,1,1,1,1,1,1,1
Panama,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Bosnia and Herzegovina,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Chad,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Belarus,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Antigua and Barbuda,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Angola,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tuvalu,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
East Asia and Pacific,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Chile,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tonga,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
"Congo, Republic of",1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Costa Rica,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Thailand,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Namibia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Sri Lanka,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Europe and Central Asia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Kiribati,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Serbia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Romania,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Poland,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Zimbabwe,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

The 10 countries with most projects by count of project IDs: China, Indonesia, Vietnam, India, Yemen, Nepal, Bangladesh, Morocco, Mozambique, and Africa. However, since Africa is not a country, I am digging deeper to see why Africa is listed as country name.

In [7]:
#Explore the borrowers that shows country name as Africa.
df_africa = sample_json_df[sample_json_df.countryshortname == 'Africa']
df_africa['borrower']

45                            ECOWAS
46                    UGANDA-COMOROS
51                  OSS, IUCN, CILSS
58                     BANK EXECUTED
65           BURUNDI,RWANDA,TANZANIA
99                GOVERNMENT OF MALI
167    MINISTRIES OF TELECOM AND ICT
184                         TANZANIA
287       MALAWI, MOZAMBIQUE, ZAMBIA
353            NILE BASIN INITIATIVE
449              GOVERNMENT OF NIGER
Name: borrower, dtype: object

In [8]:
#Explore the borrowers that shows country name as China.
df_china = sample_json_df[sample_json_df.countryshortname == 'China']
df_china['borrower']

7          PEOPLE'S REPUBLIC OF CHINA
119        PEOPLE'S REPUBLIC OF CHINA
120        PEOPLE'S REPUBLIC OF CHINA
121        PEOPLE'S REPUBLIC OF CHINA
156                    ANHUI PROVINCE
162         PEOPLES REPUBLIC OF CHINA
164                             CHINA
200        PEOPLE'S REPUBLIC OF CHINA
226               MINISTRY OF FINANCE
250               MINISTRY OF FINANCE
275               MINISTRY OF FINANCE
276        PEOPLE'S REPUBLIC OF CHINA
277    THE PEOPLE'S REPUBLIC OF CHINA
278     SHANGHAI MUNICIPAL GOVERNMENT
279     CHANGNING DISTRICT GOVERNMENT
280                        P.R. CHINA
305        PEOPLE'S REPUBLIC OF CHINA
343        PEOPLE'S REPUBLIC OF CHINA
393         PEOPLE'S REPULIC OF CHINA
Name: borrower, dtype: object

The data with countryname as Africa are projects that are either mislabeled or are joint projects by multiple countries. From the 11 entries with countryname as Africa, Tanzania appeared twice as co-borrower and sole-borrower. Therefore, the count of projects for Tanazia would be 10 instead of 8 after clarifying the entries. The assumption is also proven by checking the projects from China, the borrowers are either by the Chinese government or its state agencies. As a result, the recount of top 10 countries with most projects by project counts are:
1. China
2. Indonesia
3. Vietnam
4. India
5. Yemen
6. Nepal
7. Bangladesh
8. Morocco
9. Mozambique 
10. Tanzania
****

Next, we will explore the data by flatten the nested element in the 'mjtheme_namecode' column.

In [26]:
#Loads the file as text.
df = json.load((open('data/world_bank_projects.json')))

#Flatten the nested data in the major project theme column.
df_norm = json_normalize(df, 'mjtheme_namecode')

#Print the first 20 rows.
df_norm.head(20)

   code                                          name
0     8                             Human development
1    11
2     1                           Economic management
3     6         Social protection and risk management
4     5                         Trade and integration
5     2                      Public sector governance
6    11  Environment and natural resources management
7     6         Social protection and risk management
8     7                   Social dev/gender/inclusion
9     7                   Social dev/gender/inclusion
10    5                         Trade and integration
11    4      Financial and private sector development
12    6         Social protection and risk management
13    6
14    2                      Public sector governance
15    4      Financial and private sector development
16   11  Environment and natural resources management
17    8
18   10                             Rural development
19    7

As we can see, some of the rows have missing values in the 'name' column. Instead of grouping the major project themes by names, we can group by the theme codes below.

In [20]:
#Count the rows by code and sort.
df_norm.groupby('code').count().sort_values('name', ascending = False)

      name
code
11     250
10     216
8      210
2      199
6      168
4      146
7      130
5       77
9       50
1       38
3       15

By grouping the data by code, we find no missing values in that column. But we would still like to group and see the counts by

In [27]:
#Sort the rows by both code and missing values.
df_norm = df_norm.sort_values(['code','name'], ascending = True)

#Fill missing cells in name column with NaNs.
df_norm[df_norm['name'] == ''] = np.nan

#Backward fill the NaNs with existing code names.
df_norm = df_norm.fillna(method='bfill')

#Print the result
df_norm

     code                 name
212     1  Economic management
363     1  Economic management
1024    1  Economic management
1114    1  Economic management
1437    1  Economic management
2       1  Economic management
88      1  Economic management
175     1  Economic management
204     1  Economic management
205     1  Economic management
220     1  Economic management
222     1  Economic management
223     1  Economic management
249     1  Economic management
357     1  Economic management
453     1  Economic management
454     1  Economic management
458     1  Economic management
497     1  Economic management
647     1  Economic management
648     1  Economic management
784     1  Economic management
803     1  Economic management
841     1  Economic management
900     1  Economic management
1010    1  Economic management
1045    1  Economic management
1056    1  Economic management
1057    1  Economic management
1078    1  Economic management
...   ...                  ...
597     9    Urban development
598     9    Urban development
650     9    Urban development
669     9    Urban development
732     9    Urban development
737     9    Urban development
738     9    Urban development
739     9    Urban development
742     9    Urban development
822     9    Urban development
917     9    Urban development
930     9    Urban development
940     9    Urban development
962     9    Urban development
1095    9    Urban development
1102    9    Urban development
1103    9    Urban development
1104    9    Urban development
1166    9    Urban development
1290    9    Urban development
1303    9    Urban development
1318    9    Urban development
1342    9    Urban development
1347    9    Urban development
1425    9    Urban development
1426    9    Urban development
1428    9    Urban development
1470    9    Urban development
1473    9    Urban development
1495    9    Urban development

[1499 rows x 2 columns]

In [28]:
#Sort the count again by the theme names.
df_theme_count= df_norm.groupby('name').count().sort_values('code',ascending = False)

#Print the result again.
df_theme_count

                                              code
name
Environment and natural resources management   250
Rural development                              216
Human development                              210
Public sector governance                       199
Social protection and risk management          168
Financial and private sector development       146
Social dev/gender/inclusion                    130
Trade and integration                           77
Urban development                               50
Economic management                             38
Rule of law                                     15

The top 10 major project themes are:
+ Environment and natural resources management	
+ Rural development
+ Human development
+ Public sector governance
+ Social protection and risk management
+ Financial and private sector development
+ Social dev/gender/inclusion
+ Trade and integration
+ Urban development
+ Economic management

# Summary
****
The data reveals the top 10 countries with the most projects which include Africa by using groupby with count method. And by examine the borrower's column, the countries labeled with Africa in the 'countryshortname' shows individual country borrowers and groups of borrowing countries. Because Tanzania appeared twice as a borrowing countries in the rows that has Africa in the 'countryshortname', it is counted again twice to be determined as the 10th country with the most project. The recount of top 10 countries with most projects by project counts are:
1. China
2. Indonesia
3. Vietnam
4. India
5. Yemen
6. Nepal
7. Bangladesh
8. Morocco
9. Mozambique 
10. Tanzania

****
To examine the major project theme, the nested value of the data is flattened to show both theme name and code. The raw data shows missing names in some of the rows while all codes are present. By filling the missing values with NaN and backward fill the rows after an ascending sort, all of the rows in the 'name' column are properly labeled. Lastly, the cleaned data shows the same counts and ranking by using groupby and count method to the 'name' column as to 'code'. The top 10 major project themes are as follows:

1. Environment and natural resources management	
2. Rural development
3. Human development
4. Public sector governance
5. Social protection and risk management
6. Financial and private sector development
7. Social dev/gender/inclusion
8. Trade and integration
9. Urban development
10. Economic management
****